// Copyright (C) 2021  The GoHBase Authors.  All rights reserved.
// This file is part of GoHBase.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

package gohbase

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	operationDurationSeconds = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: "gohbase",
			Name:      "operation_duration_seconds",
			Help:      "Time in seconds for operation to complete",
			// 1.25ms, 2.5ms, 5ms, 10ms, 20ms, 40ms, ..., 1.28s, ... 20.48s, 40.96s
			Buckets: prometheus.ExponentialBuckets(0.00125, 2, 16),
		},
		[]string{"operation", "result"},
	)

	sendBatchSplitCount = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Namespace: "gohbase",
			Name:      "sendbatch_split_count",
			Help:      "Count of Region Servers hit per SendBatch",
			// 1, 2, 4, 8, 16, 32, 64, 128, 256, 512
			Buckets: prometheus.ExponentialBuckets(1, 2, 10),
		},
	)

	cachedRegionTotal = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "gohbase",
		Subsystem: "cache",
		Name:      "regions_total",
		Help:      "Total number of regions in the cache",
	})

	retryBackoffDuration = promauto.NewHistogram(prometheus.HistogramOpts{
		Namespace: "gohbase",
		Subsystem: "retry",
		Name:      "backoff_duration_seconds",
		Help:      "Time spend sleeping in retry backoff",
		// Buckets match the exact backoff time generated by the sleepAndIncreaseBackoff function
		Buckets: []float64{
			0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 1.024, 2.048,
			4.096, 8.192, 13.192, 18.192, 23.192, 28.192, 33.192,
		},
	})

	scanRenewers = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "gohbase",
		Subsystem: "scanner",
		Name:      "renewer_count",
		Help: "Number of active scanner renewers. " +
			"A continually increasing value indicates an Scanner leak.",
	})
)
