// Code generated by protoc-gen-go.
// source: ErrorHandling.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
// Protobuf version of a java.lang.StackTraceElement
// so we can serialize exceptions.
type StackTraceElementMessage struct {
	DeclaringClass   *string `protobuf:"bytes,1,opt,name=declaring_class,json=declaringClass" json:"declaring_class,omitempty"`
	MethodName       *string `protobuf:"bytes,2,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	FileName         *string `protobuf:"bytes,3,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	LineNumber       *int32  `protobuf:"varint,4,opt,name=line_number,json=lineNumber" json:"line_number,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StackTraceElementMessage) Reset()                    { *m = StackTraceElementMessage{} }
func (m *StackTraceElementMessage) String() string            { return proto.CompactTextString(m) }
func (*StackTraceElementMessage) ProtoMessage()               {}
func (*StackTraceElementMessage) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *StackTraceElementMessage) GetDeclaringClass() string {
	if m != nil && m.DeclaringClass != nil {
		return *m.DeclaringClass
	}
	return ""
}

func (m *StackTraceElementMessage) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

func (m *StackTraceElementMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *StackTraceElementMessage) GetLineNumber() int32 {
	if m != nil && m.LineNumber != nil {
		return *m.LineNumber
	}
	return 0
}

// *
// Cause of a remote failure for a generic exception. Contains
// all the information for a generic exception as well as
// optional info about the error for generic info passing
// (which should be another protobuffed class).
type GenericExceptionMessage struct {
	ClassName        *string                     `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	Message          *string                     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	ErrorInfo        []byte                      `protobuf:"bytes,3,opt,name=error_info,json=errorInfo" json:"error_info,omitempty"`
	Trace            []*StackTraceElementMessage `protobuf:"bytes,4,rep,name=trace" json:"trace,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *GenericExceptionMessage) Reset()                    { *m = GenericExceptionMessage{} }
func (m *GenericExceptionMessage) String() string            { return proto.CompactTextString(m) }
func (*GenericExceptionMessage) ProtoMessage()               {}
func (*GenericExceptionMessage) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *GenericExceptionMessage) GetClassName() string {
	if m != nil && m.ClassName != nil {
		return *m.ClassName
	}
	return ""
}

func (m *GenericExceptionMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *GenericExceptionMessage) GetErrorInfo() []byte {
	if m != nil {
		return m.ErrorInfo
	}
	return nil
}

func (m *GenericExceptionMessage) GetTrace() []*StackTraceElementMessage {
	if m != nil {
		return m.Trace
	}
	return nil
}

// *
// Exception sent across the wire when a remote task needs
// to notify other tasks that it failed and why
type ForeignExceptionMessage struct {
	Source           *string                  `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	GenericException *GenericExceptionMessage `protobuf:"bytes,2,opt,name=generic_exception,json=genericException" json:"generic_exception,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ForeignExceptionMessage) Reset()                    { *m = ForeignExceptionMessage{} }
func (m *ForeignExceptionMessage) String() string            { return proto.CompactTextString(m) }
func (*ForeignExceptionMessage) ProtoMessage()               {}
func (*ForeignExceptionMessage) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *ForeignExceptionMessage) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *ForeignExceptionMessage) GetGenericException() *GenericExceptionMessage {
	if m != nil {
		return m.GenericException
	}
	return nil
}

func init() {
	proto.RegisterType((*StackTraceElementMessage)(nil), "pb.StackTraceElementMessage")
	proto.RegisterType((*GenericExceptionMessage)(nil), "pb.GenericExceptionMessage")
	proto.RegisterType((*ForeignExceptionMessage)(nil), "pb.ForeignExceptionMessage")
}

var fileDescriptor10 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0x5f, 0x4b, 0xeb, 0x30,
	0x18, 0xc6, 0xe9, 0x76, 0x76, 0xce, 0xe9, 0xbb, 0xc3, 0x51, 0x2b, 0xb8, 0xc2, 0x14, 0x65, 0x37,
	0x0e, 0x2f, 0x72, 0xb1, 0x8f, 0x30, 0xd9, 0x9c, 0x17, 0x0e, 0xa9, 0xde, 0x97, 0x34, 0x7d, 0xd7,
	0x16, 0xdb, 0xa4, 0x24, 0x19, 0x08, 0x7e, 0x19, 0x11, 0xfc, 0x9e, 0xe6, 0xcf, 0x2a, 0xa8, 0xec,
	0xaa, 0xe4, 0xf7, 0xbc, 0x4f, 0xfa, 0x4b, 0x5a, 0x38, 0x5e, 0x48, 0x29, 0xe4, 0x8a, 0xf2, 0xbc,
	0xae, 0x78, 0x41, 0x5a, 0x29, 0xb4, 0x88, 0x7a, 0x6d, 0x36, 0x79, 0x0b, 0x20, 0x7e, 0xd0, 0x94,
	0x3d, 0x3d, 0x4a, 0xca, 0x70, 0x51, 0x63, 0x83, 0x5c, 0xdf, 0xa1, 0x52, 0xb4, 0xc0, 0xe8, 0x12,
	0x0e, 0x72, 0x64, 0x35, 0x95, 0xa6, 0x93, 0x9a, 0xa7, 0x52, 0x71, 0x70, 0x11, 0x4c, 0xc3, 0xe4,
	0xff, 0x27, 0xbe, 0xb6, 0x34, 0x3a, 0x87, 0x61, 0x83, 0xba, 0x14, 0x79, 0xca, 0x69, 0x83, 0x71,
	0xcf, 0x0d, 0x81, 0x47, 0x6b, 0x43, 0xa2, 0x31, 0x84, 0x9b, 0xaa, 0x46, 0x1f, 0xf7, 0x5d, 0xfc,
	0xd7, 0x02, 0x17, 0x9a, 0xb6, 0xb1, 0x32, 0xe1, 0xb6, 0xc9, 0x50, 0xc6, 0xbf, 0x4c, 0x3c, 0x48,
	0xc0, 0xa2, 0xb5, 0x23, 0x93, 0xf7, 0x00, 0x46, 0x37, 0xc8, 0x51, 0x56, 0x6c, 0xf1, 0xcc, 0xb0,
	0xd5, 0x95, 0xe0, 0x9d, 0xe3, 0x19, 0x80, 0x33, 0xf3, 0x5b, 0x7b, 0xbd, 0xd0, 0x11, 0xb7, 0x77,
	0x0c, 0x7f, 0x1a, 0x3f, 0xb9, 0xb3, 0xea, 0x96, 0xb6, 0x88, 0xf6, 0x52, 0xd2, 0x8a, 0x6f, 0x84,
	0x73, 0xfa, 0x97, 0x84, 0x8e, 0xdc, 0x1a, 0x10, 0xcd, 0x60, 0xa0, 0xed, 0x95, 0x18, 0x9d, 0xfe,
	0x74, 0x38, 0x3b, 0x25, 0x6d, 0x46, 0xf6, 0x5d, 0x54, 0xe2, 0x47, 0x27, 0x2f, 0x30, 0x5a, 0x0a,
	0x89, 0x55, 0xc1, 0x7f, 0x68, 0x9e, 0xc0, 0x6f, 0x25, 0xb6, 0x92, 0x75, 0x8a, 0xbb, 0x55, 0xb4,
	0x82, 0xa3, 0xc2, 0x9f, 0x2c, 0xc5, 0xae, 0xe3, 0x4c, 0x87, 0xb3, 0xb1, 0x7d, 0xe5, 0x9e, 0x63,
	0x27, 0x87, 0xc5, 0xb7, 0x60, 0xbe, 0x84, 0x2b, 0x21, 0x0b, 0x42, 0x5b, 0xca, 0x4a, 0x24, 0x25,
	0xcd, 0x85, 0x68, 0x49, 0x99, 0x51, 0x85, 0xfe, 0x73, 0x67, 0xdb, 0x0d, 0x71, 0x25, 0xaa, 0x31,
	0x9f, 0x7f, 0xfd, 0x21, 0xee, 0xed, 0x80, 0x5a, 0x05, 0xaf, 0x41, 0xf0, 0x11, 0x00, 0x00, 0xff,
	0xff, 0x59, 0x62, 0x7e, 0xbe, 0x2b, 0x02, 0x00, 0x00,
}
