//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file contains protocol buffers that are used for filters

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.28.3
// source: Filter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterList_Operator int32

const (
	FilterList_MUST_PASS_ALL FilterList_Operator = 1
	FilterList_MUST_PASS_ONE FilterList_Operator = 2
)

// Enum value maps for FilterList_Operator.
var (
	FilterList_Operator_name = map[int32]string{
		1: "MUST_PASS_ALL",
		2: "MUST_PASS_ONE",
	}
	FilterList_Operator_value = map[string]int32{
		"MUST_PASS_ALL": 1,
		"MUST_PASS_ONE": 2,
	}
)

func (x FilterList_Operator) Enum() *FilterList_Operator {
	p := new(FilterList_Operator)
	*p = x
	return p
}

func (x FilterList_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterList_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_Filter_proto_enumTypes[0].Descriptor()
}

func (FilterList_Operator) Type() protoreflect.EnumType {
	return &file_Filter_proto_enumTypes[0]
}

func (x FilterList_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FilterList_Operator) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FilterList_Operator(num)
	return nil
}

// Deprecated: Use FilterList_Operator.Descriptor instead.
func (FilterList_Operator) EnumDescriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{8, 0}
}

type Filter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	SerializedFilter []byte                 `protobuf:"bytes,2,opt,name=serialized_filter,json=serializedFilter" json:"serialized_filter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_Filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Filter) GetSerializedFilter() []byte {
	if x != nil {
		return x.SerializedFilter
	}
	return nil
}

type ColumnCountGetFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,req,name=limit" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnCountGetFilter) Reset() {
	*x = ColumnCountGetFilter{}
	mi := &file_Filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnCountGetFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnCountGetFilter) ProtoMessage() {}

func (x *ColumnCountGetFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnCountGetFilter.ProtoReflect.Descriptor instead.
func (*ColumnCountGetFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnCountGetFilter) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ColumnPaginationFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,req,name=limit" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	ColumnOffset  []byte                 `protobuf:"bytes,3,opt,name=column_offset,json=columnOffset" json:"column_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnPaginationFilter) Reset() {
	*x = ColumnPaginationFilter{}
	mi := &file_Filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnPaginationFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnPaginationFilter) ProtoMessage() {}

func (x *ColumnPaginationFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnPaginationFilter.ProtoReflect.Descriptor instead.
func (*ColumnPaginationFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnPaginationFilter) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ColumnPaginationFilter) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ColumnPaginationFilter) GetColumnOffset() []byte {
	if x != nil {
		return x.ColumnOffset
	}
	return nil
}

type ColumnPrefixFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,req,name=prefix" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnPrefixFilter) Reset() {
	*x = ColumnPrefixFilter{}
	mi := &file_Filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnPrefixFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnPrefixFilter) ProtoMessage() {}

func (x *ColumnPrefixFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnPrefixFilter.ProtoReflect.Descriptor instead.
func (*ColumnPrefixFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnPrefixFilter) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type ColumnRangeFilter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MinColumn          []byte                 `protobuf:"bytes,1,opt,name=min_column,json=minColumn" json:"min_column,omitempty"`
	MinColumnInclusive *bool                  `protobuf:"varint,2,opt,name=min_column_inclusive,json=minColumnInclusive" json:"min_column_inclusive,omitempty"`
	MaxColumn          []byte                 `protobuf:"bytes,3,opt,name=max_column,json=maxColumn" json:"max_column,omitempty"`
	MaxColumnInclusive *bool                  `protobuf:"varint,4,opt,name=max_column_inclusive,json=maxColumnInclusive" json:"max_column_inclusive,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ColumnRangeFilter) Reset() {
	*x = ColumnRangeFilter{}
	mi := &file_Filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnRangeFilter) ProtoMessage() {}

func (x *ColumnRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnRangeFilter.ProtoReflect.Descriptor instead.
func (*ColumnRangeFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{4}
}

func (x *ColumnRangeFilter) GetMinColumn() []byte {
	if x != nil {
		return x.MinColumn
	}
	return nil
}

func (x *ColumnRangeFilter) GetMinColumnInclusive() bool {
	if x != nil && x.MinColumnInclusive != nil {
		return *x.MinColumnInclusive
	}
	return false
}

func (x *ColumnRangeFilter) GetMaxColumn() []byte {
	if x != nil {
		return x.MaxColumn
	}
	return nil
}

func (x *ColumnRangeFilter) GetMaxColumnInclusive() bool {
	if x != nil && x.MaxColumnInclusive != nil {
		return *x.MaxColumnInclusive
	}
	return false
}

type CompareFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompareOp     *CompareType           `protobuf:"varint,1,req,name=compare_op,json=compareOp,enum=pb.CompareType" json:"compare_op,omitempty"`
	Comparator    *Comparator            `protobuf:"bytes,2,opt,name=comparator" json:"comparator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareFilter) Reset() {
	*x = CompareFilter{}
	mi := &file_Filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareFilter) ProtoMessage() {}

func (x *CompareFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareFilter.ProtoReflect.Descriptor instead.
func (*CompareFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{5}
}

func (x *CompareFilter) GetCompareOp() CompareType {
	if x != nil && x.CompareOp != nil {
		return *x.CompareOp
	}
	return CompareType_LESS
}

func (x *CompareFilter) GetComparator() *Comparator {
	if x != nil {
		return x.Comparator
	}
	return nil
}

type DependentColumnFilter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CompareFilter       *CompareFilter         `protobuf:"bytes,1,req,name=compare_filter,json=compareFilter" json:"compare_filter,omitempty"`
	ColumnFamily        []byte                 `protobuf:"bytes,2,opt,name=column_family,json=columnFamily" json:"column_family,omitempty"`
	ColumnQualifier     []byte                 `protobuf:"bytes,3,opt,name=column_qualifier,json=columnQualifier" json:"column_qualifier,omitempty"`
	DropDependentColumn *bool                  `protobuf:"varint,4,opt,name=drop_dependent_column,json=dropDependentColumn" json:"drop_dependent_column,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DependentColumnFilter) Reset() {
	*x = DependentColumnFilter{}
	mi := &file_Filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependentColumnFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentColumnFilter) ProtoMessage() {}

func (x *DependentColumnFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentColumnFilter.ProtoReflect.Descriptor instead.
func (*DependentColumnFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{6}
}

func (x *DependentColumnFilter) GetCompareFilter() *CompareFilter {
	if x != nil {
		return x.CompareFilter
	}
	return nil
}

func (x *DependentColumnFilter) GetColumnFamily() []byte {
	if x != nil {
		return x.ColumnFamily
	}
	return nil
}

func (x *DependentColumnFilter) GetColumnQualifier() []byte {
	if x != nil {
		return x.ColumnQualifier
	}
	return nil
}

func (x *DependentColumnFilter) GetDropDependentColumn() bool {
	if x != nil && x.DropDependentColumn != nil {
		return *x.DropDependentColumn
	}
	return false
}

type FamilyFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompareFilter *CompareFilter         `protobuf:"bytes,1,req,name=compare_filter,json=compareFilter" json:"compare_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyFilter) Reset() {
	*x = FamilyFilter{}
	mi := &file_Filter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyFilter) ProtoMessage() {}

func (x *FamilyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyFilter.ProtoReflect.Descriptor instead.
func (*FamilyFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{7}
}

func (x *FamilyFilter) GetCompareFilter() *CompareFilter {
	if x != nil {
		return x.CompareFilter
	}
	return nil
}

type FilterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *FilterList_Operator   `protobuf:"varint,1,req,name=operator,enum=pb.FilterList_Operator" json:"operator,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,2,rep,name=filters" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterList) Reset() {
	*x = FilterList{}
	mi := &file_Filter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterList) ProtoMessage() {}

func (x *FilterList) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterList.ProtoReflect.Descriptor instead.
func (*FilterList) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{8}
}

func (x *FilterList) GetOperator() FilterList_Operator {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return FilterList_MUST_PASS_ALL
}

func (x *FilterList) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type FilterWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,req,name=filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterWrapper) Reset() {
	*x = FilterWrapper{}
	mi := &file_Filter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterWrapper) ProtoMessage() {}

func (x *FilterWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterWrapper.ProtoReflect.Descriptor instead.
func (*FilterWrapper) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{9}
}

func (x *FilterWrapper) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type FirstKeyOnlyFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirstKeyOnlyFilter) Reset() {
	*x = FirstKeyOnlyFilter{}
	mi := &file_Filter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirstKeyOnlyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstKeyOnlyFilter) ProtoMessage() {}

func (x *FirstKeyOnlyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstKeyOnlyFilter.ProtoReflect.Descriptor instead.
func (*FirstKeyOnlyFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{10}
}

type FirstKeyValueMatchingQualifiersFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qualifiers    [][]byte               `protobuf:"bytes,1,rep,name=qualifiers" json:"qualifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirstKeyValueMatchingQualifiersFilter) Reset() {
	*x = FirstKeyValueMatchingQualifiersFilter{}
	mi := &file_Filter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirstKeyValueMatchingQualifiersFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstKeyValueMatchingQualifiersFilter) ProtoMessage() {}

func (x *FirstKeyValueMatchingQualifiersFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstKeyValueMatchingQualifiersFilter.ProtoReflect.Descriptor instead.
func (*FirstKeyValueMatchingQualifiersFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{11}
}

func (x *FirstKeyValueMatchingQualifiersFilter) GetQualifiers() [][]byte {
	if x != nil {
		return x.Qualifiers
	}
	return nil
}

type FuzzyRowFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuzzyKeysData []*BytesBytesPair      `protobuf:"bytes,1,rep,name=fuzzy_keys_data,json=fuzzyKeysData" json:"fuzzy_keys_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzyRowFilter) Reset() {
	*x = FuzzyRowFilter{}
	mi := &file_Filter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzyRowFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzyRowFilter) ProtoMessage() {}

func (x *FuzzyRowFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzyRowFilter.ProtoReflect.Descriptor instead.
func (*FuzzyRowFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{12}
}

func (x *FuzzyRowFilter) GetFuzzyKeysData() []*BytesBytesPair {
	if x != nil {
		return x.FuzzyKeysData
	}
	return nil
}

type InclusiveStopFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopRowKey    []byte                 `protobuf:"bytes,1,opt,name=stop_row_key,json=stopRowKey" json:"stop_row_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusiveStopFilter) Reset() {
	*x = InclusiveStopFilter{}
	mi := &file_Filter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusiveStopFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusiveStopFilter) ProtoMessage() {}

func (x *InclusiveStopFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusiveStopFilter.ProtoReflect.Descriptor instead.
func (*InclusiveStopFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{13}
}

func (x *InclusiveStopFilter) GetStopRowKey() []byte {
	if x != nil {
		return x.StopRowKey
	}
	return nil
}

type KeyOnlyFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LenAsVal      *bool                  `protobuf:"varint,1,req,name=len_as_val,json=lenAsVal" json:"len_as_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyOnlyFilter) Reset() {
	*x = KeyOnlyFilter{}
	mi := &file_Filter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyOnlyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyOnlyFilter) ProtoMessage() {}

func (x *KeyOnlyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyOnlyFilter.ProtoReflect.Descriptor instead.
func (*KeyOnlyFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{14}
}

func (x *KeyOnlyFilter) GetLenAsVal() bool {
	if x != nil && x.LenAsVal != nil {
		return *x.LenAsVal
	}
	return false
}

type MultipleColumnPrefixFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SortedPrefixes [][]byte               `protobuf:"bytes,1,rep,name=sorted_prefixes,json=sortedPrefixes" json:"sorted_prefixes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultipleColumnPrefixFilter) Reset() {
	*x = MultipleColumnPrefixFilter{}
	mi := &file_Filter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleColumnPrefixFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleColumnPrefixFilter) ProtoMessage() {}

func (x *MultipleColumnPrefixFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleColumnPrefixFilter.ProtoReflect.Descriptor instead.
func (*MultipleColumnPrefixFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{15}
}

func (x *MultipleColumnPrefixFilter) GetSortedPrefixes() [][]byte {
	if x != nil {
		return x.SortedPrefixes
	}
	return nil
}

type PageFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *int64                 `protobuf:"varint,1,req,name=page_size,json=pageSize" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageFilter) Reset() {
	*x = PageFilter{}
	mi := &file_Filter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageFilter) ProtoMessage() {}

func (x *PageFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageFilter.ProtoReflect.Descriptor instead.
func (*PageFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{16}
}

func (x *PageFilter) GetPageSize() int64 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type PrefixFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixFilter) Reset() {
	*x = PrefixFilter{}
	mi := &file_Filter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixFilter) ProtoMessage() {}

func (x *PrefixFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixFilter.ProtoReflect.Descriptor instead.
func (*PrefixFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{17}
}

func (x *PrefixFilter) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type QualifierFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompareFilter *CompareFilter         `protobuf:"bytes,1,req,name=compare_filter,json=compareFilter" json:"compare_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifierFilter) Reset() {
	*x = QualifierFilter{}
	mi := &file_Filter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifierFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifierFilter) ProtoMessage() {}

func (x *QualifierFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifierFilter.ProtoReflect.Descriptor instead.
func (*QualifierFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{18}
}

func (x *QualifierFilter) GetCompareFilter() *CompareFilter {
	if x != nil {
		return x.CompareFilter
	}
	return nil
}

type RandomRowFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chance        *float32               `protobuf:"fixed32,1,req,name=chance" json:"chance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomRowFilter) Reset() {
	*x = RandomRowFilter{}
	mi := &file_Filter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomRowFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRowFilter) ProtoMessage() {}

func (x *RandomRowFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRowFilter.ProtoReflect.Descriptor instead.
func (*RandomRowFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{19}
}

func (x *RandomRowFilter) GetChance() float32 {
	if x != nil && x.Chance != nil {
		return *x.Chance
	}
	return 0
}

type RowFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompareFilter *CompareFilter         `protobuf:"bytes,1,req,name=compare_filter,json=compareFilter" json:"compare_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowFilter) Reset() {
	*x = RowFilter{}
	mi := &file_Filter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowFilter) ProtoMessage() {}

func (x *RowFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowFilter.ProtoReflect.Descriptor instead.
func (*RowFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{20}
}

func (x *RowFilter) GetCompareFilter() *CompareFilter {
	if x != nil {
		return x.CompareFilter
	}
	return nil
}

type SingleColumnValueExcludeFilter struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	SingleColumnValueFilter *SingleColumnValueFilter `protobuf:"bytes,1,req,name=single_column_value_filter,json=singleColumnValueFilter" json:"single_column_value_filter,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SingleColumnValueExcludeFilter) Reset() {
	*x = SingleColumnValueExcludeFilter{}
	mi := &file_Filter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleColumnValueExcludeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleColumnValueExcludeFilter) ProtoMessage() {}

func (x *SingleColumnValueExcludeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleColumnValueExcludeFilter.ProtoReflect.Descriptor instead.
func (*SingleColumnValueExcludeFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{21}
}

func (x *SingleColumnValueExcludeFilter) GetSingleColumnValueFilter() *SingleColumnValueFilter {
	if x != nil {
		return x.SingleColumnValueFilter
	}
	return nil
}

type SingleColumnValueFilter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ColumnFamily      []byte                 `protobuf:"bytes,1,opt,name=column_family,json=columnFamily" json:"column_family,omitempty"`
	ColumnQualifier   []byte                 `protobuf:"bytes,2,opt,name=column_qualifier,json=columnQualifier" json:"column_qualifier,omitempty"`
	CompareOp         *CompareType           `protobuf:"varint,3,req,name=compare_op,json=compareOp,enum=pb.CompareType" json:"compare_op,omitempty"`
	Comparator        *Comparator            `protobuf:"bytes,4,req,name=comparator" json:"comparator,omitempty"`
	FilterIfMissing   *bool                  `protobuf:"varint,5,opt,name=filter_if_missing,json=filterIfMissing" json:"filter_if_missing,omitempty"`
	LatestVersionOnly *bool                  `protobuf:"varint,6,opt,name=latest_version_only,json=latestVersionOnly" json:"latest_version_only,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SingleColumnValueFilter) Reset() {
	*x = SingleColumnValueFilter{}
	mi := &file_Filter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleColumnValueFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleColumnValueFilter) ProtoMessage() {}

func (x *SingleColumnValueFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleColumnValueFilter.ProtoReflect.Descriptor instead.
func (*SingleColumnValueFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{22}
}

func (x *SingleColumnValueFilter) GetColumnFamily() []byte {
	if x != nil {
		return x.ColumnFamily
	}
	return nil
}

func (x *SingleColumnValueFilter) GetColumnQualifier() []byte {
	if x != nil {
		return x.ColumnQualifier
	}
	return nil
}

func (x *SingleColumnValueFilter) GetCompareOp() CompareType {
	if x != nil && x.CompareOp != nil {
		return *x.CompareOp
	}
	return CompareType_LESS
}

func (x *SingleColumnValueFilter) GetComparator() *Comparator {
	if x != nil {
		return x.Comparator
	}
	return nil
}

func (x *SingleColumnValueFilter) GetFilterIfMissing() bool {
	if x != nil && x.FilterIfMissing != nil {
		return *x.FilterIfMissing
	}
	return false
}

func (x *SingleColumnValueFilter) GetLatestVersionOnly() bool {
	if x != nil && x.LatestVersionOnly != nil {
		return *x.LatestVersionOnly
	}
	return false
}

type SkipFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,req,name=filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipFilter) Reset() {
	*x = SkipFilter{}
	mi := &file_Filter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipFilter) ProtoMessage() {}

func (x *SkipFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipFilter.ProtoReflect.Descriptor instead.
func (*SkipFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{23}
}

func (x *SkipFilter) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type TimestampsFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamps    []int64                `protobuf:"varint,1,rep,packed,name=timestamps" json:"timestamps,omitempty"`
	CanHint       *bool                  `protobuf:"varint,2,opt,name=can_hint,json=canHint" json:"can_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampsFilter) Reset() {
	*x = TimestampsFilter{}
	mi := &file_Filter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampsFilter) ProtoMessage() {}

func (x *TimestampsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampsFilter.ProtoReflect.Descriptor instead.
func (*TimestampsFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{24}
}

func (x *TimestampsFilter) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *TimestampsFilter) GetCanHint() bool {
	if x != nil && x.CanHint != nil {
		return *x.CanHint
	}
	return false
}

type ValueFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompareFilter *CompareFilter         `protobuf:"bytes,1,req,name=compare_filter,json=compareFilter" json:"compare_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueFilter) Reset() {
	*x = ValueFilter{}
	mi := &file_Filter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueFilter) ProtoMessage() {}

func (x *ValueFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueFilter.ProtoReflect.Descriptor instead.
func (*ValueFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{25}
}

func (x *ValueFilter) GetCompareFilter() *CompareFilter {
	if x != nil {
		return x.CompareFilter
	}
	return nil
}

type WhileMatchFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,req,name=filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhileMatchFilter) Reset() {
	*x = WhileMatchFilter{}
	mi := &file_Filter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhileMatchFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhileMatchFilter) ProtoMessage() {}

func (x *WhileMatchFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhileMatchFilter.ProtoReflect.Descriptor instead.
func (*WhileMatchFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{26}
}

func (x *WhileMatchFilter) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type FilterAllFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterAllFilter) Reset() {
	*x = FilterAllFilter{}
	mi := &file_Filter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterAllFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAllFilter) ProtoMessage() {}

func (x *FilterAllFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAllFilter.ProtoReflect.Descriptor instead.
func (*FilterAllFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{27}
}

type RowRange struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartRow          []byte                 `protobuf:"bytes,1,opt,name=start_row,json=startRow" json:"start_row,omitempty"`
	StartRowInclusive *bool                  `protobuf:"varint,2,opt,name=start_row_inclusive,json=startRowInclusive" json:"start_row_inclusive,omitempty"`
	StopRow           []byte                 `protobuf:"bytes,3,opt,name=stop_row,json=stopRow" json:"stop_row,omitempty"`
	StopRowInclusive  *bool                  `protobuf:"varint,4,opt,name=stop_row_inclusive,json=stopRowInclusive" json:"stop_row_inclusive,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RowRange) Reset() {
	*x = RowRange{}
	mi := &file_Filter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowRange) ProtoMessage() {}

func (x *RowRange) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowRange.ProtoReflect.Descriptor instead.
func (*RowRange) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{28}
}

func (x *RowRange) GetStartRow() []byte {
	if x != nil {
		return x.StartRow
	}
	return nil
}

func (x *RowRange) GetStartRowInclusive() bool {
	if x != nil && x.StartRowInclusive != nil {
		return *x.StartRowInclusive
	}
	return false
}

func (x *RowRange) GetStopRow() []byte {
	if x != nil {
		return x.StopRow
	}
	return nil
}

func (x *RowRange) GetStopRowInclusive() bool {
	if x != nil && x.StopRowInclusive != nil {
		return *x.StopRowInclusive
	}
	return false
}

type MultiRowRangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowRangeList  []*RowRange            `protobuf:"bytes,1,rep,name=row_range_list,json=rowRangeList" json:"row_range_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiRowRangeFilter) Reset() {
	*x = MultiRowRangeFilter{}
	mi := &file_Filter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRowRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRowRangeFilter) ProtoMessage() {}

func (x *MultiRowRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Filter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRowRangeFilter.ProtoReflect.Descriptor instead.
func (*MultiRowRangeFilter) Descriptor() ([]byte, []int) {
	return file_Filter_proto_rawDescGZIP(), []int{29}
}

func (x *MultiRowRangeFilter) GetRowRangeList() []*RowRange {
	if x != nil {
		return x.RowRangeList
	}
	return nil
}

var File_Filter_proto protoreflect.FileDescriptor

var file_Filter_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0b, 0x48, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x10, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x49, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2b, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x14,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x6b, 0x0a, 0x16, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x2c, 0x0a, 0x12, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0xb5, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x69,
	0x6e, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x6d,
	0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x6d, 0x61, 0x78, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0x6f, 0x0a,
	0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x4f, 0x70, 0x12, 0x2e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xd5,
	0x01, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x66, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x32, 0x0a, 0x15, 0x64, 0x72, 0x6f, 0x70, 0x5f, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x13, 0x64, 0x72, 0x6f, 0x70, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x48, 0x0a, 0x0c, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x22, 0x99, 0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x33, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x08, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x55, 0x53, 0x54, 0x5f, 0x50,
	0x41, 0x53, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x55, 0x53,
	0x54, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x22, 0x33, 0x0a, 0x0d,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x22, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x4f, 0x6e, 0x6c,
	0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x47, 0x0a, 0x25, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73,
	0x22, 0x4c, 0x0a, 0x0e, 0x46, 0x75, 0x7a, 0x7a, 0x79, 0x52, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0f, 0x66, 0x75, 0x7a, 0x7a, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x73,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x0d, 0x66, 0x75, 0x7a, 0x7a, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x37,
	0x0a, 0x13, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x6f,
	0x77, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x74, 0x6f,
	0x70, 0x52, 0x6f, 0x77, 0x4b, 0x65, 0x79, 0x22, 0x2d, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x4f, 0x6e,
	0x6c, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x0a, 0x6c, 0x65, 0x6e, 0x5f,
	0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x65,
	0x6e, 0x41, 0x73, 0x56, 0x61, 0x6c, 0x22, 0x45, 0x0a, 0x1a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0e, 0x73,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x22, 0x29, 0x0a,
	0x0a, 0x50, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x26, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x22, 0x4b, 0x0a, 0x0f, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0d,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x29, 0x0a,
	0x0f, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02,
	0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x45, 0x0a, 0x09, 0x52, 0x6f, 0x77, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x7a, 0x0a, 0x1e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x58, 0x0a, 0x1a, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x17, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xa5, 0x02, 0x0a, 0x17,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x10,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x51, 0x75,
	0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x5f, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x4f, 0x70, 0x12, 0x2e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x66, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x66, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x13, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x11, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4f,
	0x6e, 0x6c, 0x79, 0x22, 0x30, 0x0a, 0x0a, 0x53, 0x6b, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x42, 0x02, 0x10,
	0x01, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x61, 0x6e, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x63, 0x61, 0x6e, 0x48, 0x69, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x22, 0x36, 0x0a, 0x10, 0x57, 0x68, 0x69, 0x6c, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xa0, 0x01, 0x0a,
	0x08, 0x52, 0x6f, 0x77, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x6f, 0x77, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x72, 0x6f, 0x77, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x6f, 0x77, 0x49, 0x6e, 0x63,
	0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x72,
	0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x70, 0x52, 0x6f,
	0x77, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x72, 0x6f, 0x77, 0x5f, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73,
	0x74, 0x6f, 0x70, 0x52, 0x6f, 0x77, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22,
	0x49, 0x0a, 0x13, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x6f, 0x77, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x0e, 0x72, 0x6f, 0x77, 0x5f, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0c, 0x72, 0x6f,
	0x77, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x49, 0x0a, 0x2a, 0x6f, 0x72,
	0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x48, 0x01, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x88,
	0x01, 0x01, 0xa0, 0x01, 0x01,
})

var (
	file_Filter_proto_rawDescOnce sync.Once
	file_Filter_proto_rawDescData []byte
)

func file_Filter_proto_rawDescGZIP() []byte {
	file_Filter_proto_rawDescOnce.Do(func() {
		file_Filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Filter_proto_rawDesc), len(file_Filter_proto_rawDesc)))
	})
	return file_Filter_proto_rawDescData
}

var file_Filter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Filter_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_Filter_proto_goTypes = []any{
	(FilterList_Operator)(0),                      // 0: pb.FilterList.Operator
	(*Filter)(nil),                                // 1: pb.Filter
	(*ColumnCountGetFilter)(nil),                  // 2: pb.ColumnCountGetFilter
	(*ColumnPaginationFilter)(nil),                // 3: pb.ColumnPaginationFilter
	(*ColumnPrefixFilter)(nil),                    // 4: pb.ColumnPrefixFilter
	(*ColumnRangeFilter)(nil),                     // 5: pb.ColumnRangeFilter
	(*CompareFilter)(nil),                         // 6: pb.CompareFilter
	(*DependentColumnFilter)(nil),                 // 7: pb.DependentColumnFilter
	(*FamilyFilter)(nil),                          // 8: pb.FamilyFilter
	(*FilterList)(nil),                            // 9: pb.FilterList
	(*FilterWrapper)(nil),                         // 10: pb.FilterWrapper
	(*FirstKeyOnlyFilter)(nil),                    // 11: pb.FirstKeyOnlyFilter
	(*FirstKeyValueMatchingQualifiersFilter)(nil), // 12: pb.FirstKeyValueMatchingQualifiersFilter
	(*FuzzyRowFilter)(nil),                        // 13: pb.FuzzyRowFilter
	(*InclusiveStopFilter)(nil),                   // 14: pb.InclusiveStopFilter
	(*KeyOnlyFilter)(nil),                         // 15: pb.KeyOnlyFilter
	(*MultipleColumnPrefixFilter)(nil),            // 16: pb.MultipleColumnPrefixFilter
	(*PageFilter)(nil),                            // 17: pb.PageFilter
	(*PrefixFilter)(nil),                          // 18: pb.PrefixFilter
	(*QualifierFilter)(nil),                       // 19: pb.QualifierFilter
	(*RandomRowFilter)(nil),                       // 20: pb.RandomRowFilter
	(*RowFilter)(nil),                             // 21: pb.RowFilter
	(*SingleColumnValueExcludeFilter)(nil),        // 22: pb.SingleColumnValueExcludeFilter
	(*SingleColumnValueFilter)(nil),               // 23: pb.SingleColumnValueFilter
	(*SkipFilter)(nil),                            // 24: pb.SkipFilter
	(*TimestampsFilter)(nil),                      // 25: pb.TimestampsFilter
	(*ValueFilter)(nil),                           // 26: pb.ValueFilter
	(*WhileMatchFilter)(nil),                      // 27: pb.WhileMatchFilter
	(*FilterAllFilter)(nil),                       // 28: pb.FilterAllFilter
	(*RowRange)(nil),                              // 29: pb.RowRange
	(*MultiRowRangeFilter)(nil),                   // 30: pb.MultiRowRangeFilter
	(CompareType)(0),                              // 31: pb.CompareType
	(*Comparator)(nil),                            // 32: pb.Comparator
	(*BytesBytesPair)(nil),                        // 33: pb.BytesBytesPair
}
var file_Filter_proto_depIdxs = []int32{
	31, // 0: pb.CompareFilter.compare_op:type_name -> pb.CompareType
	32, // 1: pb.CompareFilter.comparator:type_name -> pb.Comparator
	6,  // 2: pb.DependentColumnFilter.compare_filter:type_name -> pb.CompareFilter
	6,  // 3: pb.FamilyFilter.compare_filter:type_name -> pb.CompareFilter
	0,  // 4: pb.FilterList.operator:type_name -> pb.FilterList.Operator
	1,  // 5: pb.FilterList.filters:type_name -> pb.Filter
	1,  // 6: pb.FilterWrapper.filter:type_name -> pb.Filter
	33, // 7: pb.FuzzyRowFilter.fuzzy_keys_data:type_name -> pb.BytesBytesPair
	6,  // 8: pb.QualifierFilter.compare_filter:type_name -> pb.CompareFilter
	6,  // 9: pb.RowFilter.compare_filter:type_name -> pb.CompareFilter
	23, // 10: pb.SingleColumnValueExcludeFilter.single_column_value_filter:type_name -> pb.SingleColumnValueFilter
	31, // 11: pb.SingleColumnValueFilter.compare_op:type_name -> pb.CompareType
	32, // 12: pb.SingleColumnValueFilter.comparator:type_name -> pb.Comparator
	1,  // 13: pb.SkipFilter.filter:type_name -> pb.Filter
	6,  // 14: pb.ValueFilter.compare_filter:type_name -> pb.CompareFilter
	1,  // 15: pb.WhileMatchFilter.filter:type_name -> pb.Filter
	29, // 16: pb.MultiRowRangeFilter.row_range_list:type_name -> pb.RowRange
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_Filter_proto_init() }
func file_Filter_proto_init() {
	if File_Filter_proto != nil {
		return
	}
	file_HBase_proto_init()
	file_Comparator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Filter_proto_rawDesc), len(file_Filter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Filter_proto_goTypes,
		DependencyIndexes: file_Filter_proto_depIdxs,
		EnumInfos:         file_Filter_proto_enumTypes,
		MessageInfos:      file_Filter_proto_msgTypes,
	}.Build()
	File_Filter_proto = out.File
	file_Filter_proto_goTypes = nil
	file_Filter_proto_depIdxs = nil
}
