//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: Replication.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationState_State int32

const (
	ReplicationState_ENABLED  ReplicationState_State = 0
	ReplicationState_DISABLED ReplicationState_State = 1
)

// Enum value maps for ReplicationState_State.
var (
	ReplicationState_State_name = map[int32]string{
		0: "ENABLED",
		1: "DISABLED",
	}
	ReplicationState_State_value = map[string]int32{
		"ENABLED":  0,
		"DISABLED": 1,
	}
)

func (x ReplicationState_State) Enum() *ReplicationState_State {
	p := new(ReplicationState_State)
	*p = x
	return p
}

func (x ReplicationState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_Replication_proto_enumTypes[0].Descriptor()
}

func (ReplicationState_State) Type() protoreflect.EnumType {
	return &file_Replication_proto_enumTypes[0]
}

func (x ReplicationState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ReplicationState_State) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ReplicationState_State(num)
	return nil
}

// Deprecated: Use ReplicationState_State.Descriptor instead.
func (ReplicationState_State) EnumDescriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{2, 0}
}

type TableCF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     *TableName             `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Families      [][]byte               `protobuf:"bytes,2,rep,name=families" json:"families,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableCF) Reset() {
	*x = TableCF{}
	mi := &file_Replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableCF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCF) ProtoMessage() {}

func (x *TableCF) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCF.ProtoReflect.Descriptor instead.
func (*TableCF) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{0}
}

func (x *TableCF) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *TableCF) GetFamilies() [][]byte {
	if x != nil {
		return x.Families
	}
	return nil
}

// *
// Used by replication. Holds a replication peer key.
type ReplicationPeer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// clusterkey is the concatenation of the slave cluster's
	// hbase.zookeeper.quorum:hbase.zookeeper.property.clientPort:zookeeper.znode.parent
	Clusterkey              *string           `protobuf:"bytes,1,opt,name=clusterkey" json:"clusterkey,omitempty"`
	ReplicationEndpointImpl *string           `protobuf:"bytes,2,opt,name=replicationEndpointImpl" json:"replicationEndpointImpl,omitempty"`
	Data                    []*BytesBytesPair `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
	Configuration           []*NameStringPair `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
	TableCfs                []*TableCF        `protobuf:"bytes,5,rep,name=table_cfs,json=tableCfs" json:"table_cfs,omitempty"`
	Namespaces              [][]byte          `protobuf:"bytes,6,rep,name=namespaces" json:"namespaces,omitempty"`
	Bandwidth               *int64            `protobuf:"varint,7,opt,name=bandwidth" json:"bandwidth,omitempty"`
	ReplicateAll            *bool             `protobuf:"varint,8,opt,name=replicate_all,json=replicateAll" json:"replicate_all,omitempty"`
	ExcludeTableCfs         []*TableCF        `protobuf:"bytes,9,rep,name=exclude_table_cfs,json=excludeTableCfs" json:"exclude_table_cfs,omitempty"`
	ExcludeNamespaces       [][]byte          `protobuf:"bytes,10,rep,name=exclude_namespaces,json=excludeNamespaces" json:"exclude_namespaces,omitempty"`
	Serial                  *bool             `protobuf:"varint,11,opt,name=serial" json:"serial,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReplicationPeer) Reset() {
	*x = ReplicationPeer{}
	mi := &file_Replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationPeer) ProtoMessage() {}

func (x *ReplicationPeer) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationPeer.ProtoReflect.Descriptor instead.
func (*ReplicationPeer) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationPeer) GetClusterkey() string {
	if x != nil && x.Clusterkey != nil {
		return *x.Clusterkey
	}
	return ""
}

func (x *ReplicationPeer) GetReplicationEndpointImpl() string {
	if x != nil && x.ReplicationEndpointImpl != nil {
		return *x.ReplicationEndpointImpl
	}
	return ""
}

func (x *ReplicationPeer) GetData() []*BytesBytesPair {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReplicationPeer) GetConfiguration() []*NameStringPair {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *ReplicationPeer) GetTableCfs() []*TableCF {
	if x != nil {
		return x.TableCfs
	}
	return nil
}

func (x *ReplicationPeer) GetNamespaces() [][]byte {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ReplicationPeer) GetBandwidth() int64 {
	if x != nil && x.Bandwidth != nil {
		return *x.Bandwidth
	}
	return 0
}

func (x *ReplicationPeer) GetReplicateAll() bool {
	if x != nil && x.ReplicateAll != nil {
		return *x.ReplicateAll
	}
	return false
}

func (x *ReplicationPeer) GetExcludeTableCfs() []*TableCF {
	if x != nil {
		return x.ExcludeTableCfs
	}
	return nil
}

func (x *ReplicationPeer) GetExcludeNamespaces() [][]byte {
	if x != nil {
		return x.ExcludeNamespaces
	}
	return nil
}

func (x *ReplicationPeer) GetSerial() bool {
	if x != nil && x.Serial != nil {
		return *x.Serial
	}
	return false
}

// *
// Used by replication. Holds whether enabled or disabled
type ReplicationState struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	State         *ReplicationState_State `protobuf:"varint,1,req,name=state,enum=pb.ReplicationState_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationState) Reset() {
	*x = ReplicationState{}
	mi := &file_Replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationState) ProtoMessage() {}

func (x *ReplicationState) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationState.ProtoReflect.Descriptor instead.
func (*ReplicationState) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicationState) GetState() ReplicationState_State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ReplicationState_ENABLED
}

// *
// Used by replication. Description of the replication peer.
type ReplicationPeerDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	State         *ReplicationState      `protobuf:"bytes,2,req,name=state" json:"state,omitempty"`
	Config        *ReplicationPeer       `protobuf:"bytes,3,req,name=config" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationPeerDescription) Reset() {
	*x = ReplicationPeerDescription{}
	mi := &file_Replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationPeerDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationPeerDescription) ProtoMessage() {}

func (x *ReplicationPeerDescription) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationPeerDescription.ProtoReflect.Descriptor instead.
func (*ReplicationPeerDescription) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicationPeerDescription) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ReplicationPeerDescription) GetState() *ReplicationState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ReplicationPeerDescription) GetConfig() *ReplicationPeer {
	if x != nil {
		return x.Config
	}
	return nil
}

// *
// Used by replication. Holds the current position in an WAL file.
type ReplicationHLogPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *int64                 `protobuf:"varint,1,req,name=position" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationHLogPosition) Reset() {
	*x = ReplicationHLogPosition{}
	mi := &file_Replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationHLogPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationHLogPosition) ProtoMessage() {}

func (x *ReplicationHLogPosition) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationHLogPosition.ProtoReflect.Descriptor instead.
func (*ReplicationHLogPosition) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicationHLogPosition) GetPosition() int64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

type AddReplicationPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	PeerConfig    *ReplicationPeer       `protobuf:"bytes,2,req,name=peer_config,json=peerConfig" json:"peer_config,omitempty"`
	PeerState     *ReplicationState      `protobuf:"bytes,3,req,name=peer_state,json=peerState" json:"peer_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplicationPeerRequest) Reset() {
	*x = AddReplicationPeerRequest{}
	mi := &file_Replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplicationPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplicationPeerRequest) ProtoMessage() {}

func (x *AddReplicationPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplicationPeerRequest.ProtoReflect.Descriptor instead.
func (*AddReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{5}
}

func (x *AddReplicationPeerRequest) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

func (x *AddReplicationPeerRequest) GetPeerConfig() *ReplicationPeer {
	if x != nil {
		return x.PeerConfig
	}
	return nil
}

func (x *AddReplicationPeerRequest) GetPeerState() *ReplicationState {
	if x != nil {
		return x.PeerState
	}
	return nil
}

type AddReplicationPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcId        *uint64                `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplicationPeerResponse) Reset() {
	*x = AddReplicationPeerResponse{}
	mi := &file_Replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplicationPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplicationPeerResponse) ProtoMessage() {}

func (x *AddReplicationPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplicationPeerResponse.ProtoReflect.Descriptor instead.
func (*AddReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{6}
}

func (x *AddReplicationPeerResponse) GetProcId() uint64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

type RemoveReplicationPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReplicationPeerRequest) Reset() {
	*x = RemoveReplicationPeerRequest{}
	mi := &file_Replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReplicationPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReplicationPeerRequest) ProtoMessage() {}

func (x *RemoveReplicationPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReplicationPeerRequest.ProtoReflect.Descriptor instead.
func (*RemoveReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveReplicationPeerRequest) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

type RemoveReplicationPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcId        *uint64                `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReplicationPeerResponse) Reset() {
	*x = RemoveReplicationPeerResponse{}
	mi := &file_Replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReplicationPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReplicationPeerResponse) ProtoMessage() {}

func (x *RemoveReplicationPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReplicationPeerResponse.ProtoReflect.Descriptor instead.
func (*RemoveReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveReplicationPeerResponse) GetProcId() uint64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

type EnableReplicationPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableReplicationPeerRequest) Reset() {
	*x = EnableReplicationPeerRequest{}
	mi := &file_Replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableReplicationPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableReplicationPeerRequest) ProtoMessage() {}

func (x *EnableReplicationPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableReplicationPeerRequest.ProtoReflect.Descriptor instead.
func (*EnableReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{9}
}

func (x *EnableReplicationPeerRequest) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

type EnableReplicationPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcId        *uint64                `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableReplicationPeerResponse) Reset() {
	*x = EnableReplicationPeerResponse{}
	mi := &file_Replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableReplicationPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableReplicationPeerResponse) ProtoMessage() {}

func (x *EnableReplicationPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableReplicationPeerResponse.ProtoReflect.Descriptor instead.
func (*EnableReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{10}
}

func (x *EnableReplicationPeerResponse) GetProcId() uint64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

type DisableReplicationPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableReplicationPeerRequest) Reset() {
	*x = DisableReplicationPeerRequest{}
	mi := &file_Replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableReplicationPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableReplicationPeerRequest) ProtoMessage() {}

func (x *DisableReplicationPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableReplicationPeerRequest.ProtoReflect.Descriptor instead.
func (*DisableReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{11}
}

func (x *DisableReplicationPeerRequest) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

type DisableReplicationPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcId        *uint64                `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableReplicationPeerResponse) Reset() {
	*x = DisableReplicationPeerResponse{}
	mi := &file_Replication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableReplicationPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableReplicationPeerResponse) ProtoMessage() {}

func (x *DisableReplicationPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableReplicationPeerResponse.ProtoReflect.Descriptor instead.
func (*DisableReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{12}
}

func (x *DisableReplicationPeerResponse) GetProcId() uint64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

type GetReplicationPeerConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationPeerConfigRequest) Reset() {
	*x = GetReplicationPeerConfigRequest{}
	mi := &file_Replication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationPeerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationPeerConfigRequest) ProtoMessage() {}

func (x *GetReplicationPeerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationPeerConfigRequest.ProtoReflect.Descriptor instead.
func (*GetReplicationPeerConfigRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{13}
}

func (x *GetReplicationPeerConfigRequest) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

type GetReplicationPeerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	PeerConfig    *ReplicationPeer       `protobuf:"bytes,2,req,name=peer_config,json=peerConfig" json:"peer_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationPeerConfigResponse) Reset() {
	*x = GetReplicationPeerConfigResponse{}
	mi := &file_Replication_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationPeerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationPeerConfigResponse) ProtoMessage() {}

func (x *GetReplicationPeerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationPeerConfigResponse.ProtoReflect.Descriptor instead.
func (*GetReplicationPeerConfigResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{14}
}

func (x *GetReplicationPeerConfigResponse) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

func (x *GetReplicationPeerConfigResponse) GetPeerConfig() *ReplicationPeer {
	if x != nil {
		return x.PeerConfig
	}
	return nil
}

type UpdateReplicationPeerConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	PeerConfig    *ReplicationPeer       `protobuf:"bytes,2,req,name=peer_config,json=peerConfig" json:"peer_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplicationPeerConfigRequest) Reset() {
	*x = UpdateReplicationPeerConfigRequest{}
	mi := &file_Replication_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicationPeerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicationPeerConfigRequest) ProtoMessage() {}

func (x *UpdateReplicationPeerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicationPeerConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplicationPeerConfigRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateReplicationPeerConfigRequest) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

func (x *UpdateReplicationPeerConfigRequest) GetPeerConfig() *ReplicationPeer {
	if x != nil {
		return x.PeerConfig
	}
	return nil
}

type UpdateReplicationPeerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcId        *uint64                `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplicationPeerConfigResponse) Reset() {
	*x = UpdateReplicationPeerConfigResponse{}
	mi := &file_Replication_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicationPeerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicationPeerConfigResponse) ProtoMessage() {}

func (x *UpdateReplicationPeerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicationPeerConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateReplicationPeerConfigResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateReplicationPeerConfigResponse) GetProcId() uint64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

type ListReplicationPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regex         *string                `protobuf:"bytes,1,opt,name=regex" json:"regex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationPeersRequest) Reset() {
	*x = ListReplicationPeersRequest{}
	mi := &file_Replication_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationPeersRequest) ProtoMessage() {}

func (x *ListReplicationPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationPeersRequest.ProtoReflect.Descriptor instead.
func (*ListReplicationPeersRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{17}
}

func (x *ListReplicationPeersRequest) GetRegex() string {
	if x != nil && x.Regex != nil {
		return *x.Regex
	}
	return ""
}

type ListReplicationPeersResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	PeerDesc      []*ReplicationPeerDescription `protobuf:"bytes,1,rep,name=peer_desc,json=peerDesc" json:"peer_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationPeersResponse) Reset() {
	*x = ListReplicationPeersResponse{}
	mi := &file_Replication_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationPeersResponse) ProtoMessage() {}

func (x *ListReplicationPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationPeersResponse.ProtoReflect.Descriptor instead.
func (*ListReplicationPeersResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{18}
}

func (x *ListReplicationPeersResponse) GetPeerDesc() []*ReplicationPeerDescription {
	if x != nil {
		return x.PeerDesc
	}
	return nil
}

type GetReplicationPeerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        *string                `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationPeerStateRequest) Reset() {
	*x = GetReplicationPeerStateRequest{}
	mi := &file_Replication_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationPeerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationPeerStateRequest) ProtoMessage() {}

func (x *GetReplicationPeerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationPeerStateRequest.ProtoReflect.Descriptor instead.
func (*GetReplicationPeerStateRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{19}
}

func (x *GetReplicationPeerStateRequest) GetPeerId() string {
	if x != nil && x.PeerId != nil {
		return *x.PeerId
	}
	return ""
}

type GetReplicationPeerStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     *bool                  `protobuf:"varint,1,req,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationPeerStateResponse) Reset() {
	*x = GetReplicationPeerStateResponse{}
	mi := &file_Replication_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationPeerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationPeerStateResponse) ProtoMessage() {}

func (x *GetReplicationPeerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationPeerStateResponse.ProtoReflect.Descriptor instead.
func (*GetReplicationPeerStateResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{20}
}

func (x *GetReplicationPeerStateResponse) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

type ReplicationPeerModificationSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	On            *bool                  `protobuf:"varint,1,req,name=on" json:"on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationPeerModificationSwitchRequest) Reset() {
	*x = ReplicationPeerModificationSwitchRequest{}
	mi := &file_Replication_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationPeerModificationSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationPeerModificationSwitchRequest) ProtoMessage() {}

func (x *ReplicationPeerModificationSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationPeerModificationSwitchRequest.ProtoReflect.Descriptor instead.
func (*ReplicationPeerModificationSwitchRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{21}
}

func (x *ReplicationPeerModificationSwitchRequest) GetOn() bool {
	if x != nil && x.On != nil {
		return *x.On
	}
	return false
}

type ReplicationPeerModificationSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreviousValue *bool                  `protobuf:"varint,1,req,name=previous_value,json=previousValue" json:"previous_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationPeerModificationSwitchResponse) Reset() {
	*x = ReplicationPeerModificationSwitchResponse{}
	mi := &file_Replication_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationPeerModificationSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationPeerModificationSwitchResponse) ProtoMessage() {}

func (x *ReplicationPeerModificationSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationPeerModificationSwitchResponse.ProtoReflect.Descriptor instead.
func (*ReplicationPeerModificationSwitchResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{22}
}

func (x *ReplicationPeerModificationSwitchResponse) GetPreviousValue() bool {
	if x != nil && x.PreviousValue != nil {
		return *x.PreviousValue
	}
	return false
}

type ReplicationPeerModificationState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	On            *bool                  `protobuf:"varint,1,req,name=on" json:"on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationPeerModificationState) Reset() {
	*x = ReplicationPeerModificationState{}
	mi := &file_Replication_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationPeerModificationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationPeerModificationState) ProtoMessage() {}

func (x *ReplicationPeerModificationState) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationPeerModificationState.ProtoReflect.Descriptor instead.
func (*ReplicationPeerModificationState) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{23}
}

func (x *ReplicationPeerModificationState) GetOn() bool {
	if x != nil && x.On != nil {
		return *x.On
	}
	return false
}

type GetReplicationPeerModificationProceduresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationPeerModificationProceduresRequest) Reset() {
	*x = GetReplicationPeerModificationProceduresRequest{}
	mi := &file_Replication_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationPeerModificationProceduresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationPeerModificationProceduresRequest) ProtoMessage() {}

func (x *GetReplicationPeerModificationProceduresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationPeerModificationProceduresRequest.ProtoReflect.Descriptor instead.
func (*GetReplicationPeerModificationProceduresRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{24}
}

type GetReplicationPeerModificationProceduresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procedure     []*Procedure           `protobuf:"bytes,1,rep,name=procedure" json:"procedure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationPeerModificationProceduresResponse) Reset() {
	*x = GetReplicationPeerModificationProceduresResponse{}
	mi := &file_Replication_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationPeerModificationProceduresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationPeerModificationProceduresResponse) ProtoMessage() {}

func (x *GetReplicationPeerModificationProceduresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationPeerModificationProceduresResponse.ProtoReflect.Descriptor instead.
func (*GetReplicationPeerModificationProceduresResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{25}
}

func (x *GetReplicationPeerModificationProceduresResponse) GetProcedure() []*Procedure {
	if x != nil {
		return x.Procedure
	}
	return nil
}

type IsReplicationPeerModificationEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReplicationPeerModificationEnabledRequest) Reset() {
	*x = IsReplicationPeerModificationEnabledRequest{}
	mi := &file_Replication_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReplicationPeerModificationEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReplicationPeerModificationEnabledRequest) ProtoMessage() {}

func (x *IsReplicationPeerModificationEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReplicationPeerModificationEnabledRequest.ProtoReflect.Descriptor instead.
func (*IsReplicationPeerModificationEnabledRequest) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{26}
}

type IsReplicationPeerModificationEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,req,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReplicationPeerModificationEnabledResponse) Reset() {
	*x = IsReplicationPeerModificationEnabledResponse{}
	mi := &file_Replication_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReplicationPeerModificationEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReplicationPeerModificationEnabledResponse) ProtoMessage() {}

func (x *IsReplicationPeerModificationEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReplicationPeerModificationEnabledResponse.ProtoReflect.Descriptor instead.
func (*IsReplicationPeerModificationEnabledResponse) Descriptor() ([]byte, []int) {
	return file_Replication_proto_rawDescGZIP(), []int{27}
}

func (x *IsReplicationPeerModificationEnabledResponse) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

var File_Replication_proto protoreflect.FileDescriptor

const file_Replication_proto_rawDesc = "" +
	"\n" +
	"\x11Replication.proto\x12\x02pb\x1a\vHBase.proto\x1a\x0fProcedure.proto\"S\n" +
	"\aTableCF\x12,\n" +
	"\n" +
	"table_name\x18\x01 \x01(\v2\r.pb.TableNameR\ttableName\x12\x1a\n" +
	"\bfamilies\x18\x02 \x03(\fR\bfamilies\"\xda\x03\n" +
	"\x0fReplicationPeer\x12\x1e\n" +
	"\n" +
	"clusterkey\x18\x01 \x01(\tR\n" +
	"clusterkey\x128\n" +
	"\x17replicationEndpointImpl\x18\x02 \x01(\tR\x17replicationEndpointImpl\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.BytesBytesPairR\x04data\x128\n" +
	"\rconfiguration\x18\x04 \x03(\v2\x12.pb.NameStringPairR\rconfiguration\x12(\n" +
	"\ttable_cfs\x18\x05 \x03(\v2\v.pb.TableCFR\btableCfs\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x06 \x03(\fR\n" +
	"namespaces\x12\x1c\n" +
	"\tbandwidth\x18\a \x01(\x03R\tbandwidth\x12#\n" +
	"\rreplicate_all\x18\b \x01(\bR\freplicateAll\x127\n" +
	"\x11exclude_table_cfs\x18\t \x03(\v2\v.pb.TableCFR\x0fexcludeTableCfs\x12-\n" +
	"\x12exclude_namespaces\x18\n" +
	" \x03(\fR\x11excludeNamespaces\x12\x16\n" +
	"\x06serial\x18\v \x01(\bR\x06serial\"h\n" +
	"\x10ReplicationState\x120\n" +
	"\x05state\x18\x01 \x02(\x0e2\x1a.pb.ReplicationState.StateR\x05state\"\"\n" +
	"\x05State\x12\v\n" +
	"\aENABLED\x10\x00\x12\f\n" +
	"\bDISABLED\x10\x01\"\x85\x01\n" +
	"\x1aReplicationPeerDescription\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\tR\x02id\x12*\n" +
	"\x05state\x18\x02 \x02(\v2\x14.pb.ReplicationStateR\x05state\x12+\n" +
	"\x06config\x18\x03 \x02(\v2\x13.pb.ReplicationPeerR\x06config\"5\n" +
	"\x17ReplicationHLogPosition\x12\x1a\n" +
	"\bposition\x18\x01 \x02(\x03R\bposition\"\x9f\x01\n" +
	"\x19AddReplicationPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\x124\n" +
	"\vpeer_config\x18\x02 \x02(\v2\x13.pb.ReplicationPeerR\n" +
	"peerConfig\x123\n" +
	"\n" +
	"peer_state\x18\x03 \x02(\v2\x14.pb.ReplicationStateR\tpeerState\"5\n" +
	"\x1aAddReplicationPeerResponse\x12\x17\n" +
	"\aproc_id\x18\x01 \x01(\x04R\x06procId\"7\n" +
	"\x1cRemoveReplicationPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\"8\n" +
	"\x1dRemoveReplicationPeerResponse\x12\x17\n" +
	"\aproc_id\x18\x01 \x01(\x04R\x06procId\"7\n" +
	"\x1cEnableReplicationPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\"8\n" +
	"\x1dEnableReplicationPeerResponse\x12\x17\n" +
	"\aproc_id\x18\x01 \x01(\x04R\x06procId\"8\n" +
	"\x1dDisableReplicationPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\"9\n" +
	"\x1eDisableReplicationPeerResponse\x12\x17\n" +
	"\aproc_id\x18\x01 \x01(\x04R\x06procId\":\n" +
	"\x1fGetReplicationPeerConfigRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\"q\n" +
	" GetReplicationPeerConfigResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\x124\n" +
	"\vpeer_config\x18\x02 \x02(\v2\x13.pb.ReplicationPeerR\n" +
	"peerConfig\"s\n" +
	"\"UpdateReplicationPeerConfigRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\x124\n" +
	"\vpeer_config\x18\x02 \x02(\v2\x13.pb.ReplicationPeerR\n" +
	"peerConfig\">\n" +
	"#UpdateReplicationPeerConfigResponse\x12\x17\n" +
	"\aproc_id\x18\x01 \x01(\x04R\x06procId\"3\n" +
	"\x1bListReplicationPeersRequest\x12\x14\n" +
	"\x05regex\x18\x01 \x01(\tR\x05regex\"[\n" +
	"\x1cListReplicationPeersResponse\x12;\n" +
	"\tpeer_desc\x18\x01 \x03(\v2\x1e.pb.ReplicationPeerDescriptionR\bpeerDesc\"9\n" +
	"\x1eGetReplicationPeerStateRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x02(\tR\x06peerId\"@\n" +
	"\x1fGetReplicationPeerStateResponse\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x01 \x02(\bR\tisEnabled\":\n" +
	"(ReplicationPeerModificationSwitchRequest\x12\x0e\n" +
	"\x02on\x18\x01 \x02(\bR\x02on\"R\n" +
	")ReplicationPeerModificationSwitchResponse\x12%\n" +
	"\x0eprevious_value\x18\x01 \x02(\bR\rpreviousValue\"2\n" +
	" ReplicationPeerModificationState\x12\x0e\n" +
	"\x02on\x18\x01 \x02(\bR\x02on\"1\n" +
	"/GetReplicationPeerModificationProceduresRequest\"_\n" +
	"0GetReplicationPeerModificationProceduresResponse\x12+\n" +
	"\tprocedure\x18\x01 \x03(\v2\r.pb.ProcedureR\tprocedure\"-\n" +
	"+IsReplicationPeerModificationEnabledRequest\"H\n" +
	",IsReplicationPeerModificationEnabledResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x02(\bR\aenabledBN\n" +
	"*org.apache.hadoop.hbase.protobuf.generatedB\x11ReplicationProtosH\x01Z\x05../pb\x88\x01\x01\xa0\x01\x01"

var (
	file_Replication_proto_rawDescOnce sync.Once
	file_Replication_proto_rawDescData []byte
)

func file_Replication_proto_rawDescGZIP() []byte {
	file_Replication_proto_rawDescOnce.Do(func() {
		file_Replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Replication_proto_rawDesc), len(file_Replication_proto_rawDesc)))
	})
	return file_Replication_proto_rawDescData
}

var file_Replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Replication_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_Replication_proto_goTypes = []any{
	(ReplicationState_State)(0),                              // 0: pb.ReplicationState.State
	(*TableCF)(nil),                                          // 1: pb.TableCF
	(*ReplicationPeer)(nil),                                  // 2: pb.ReplicationPeer
	(*ReplicationState)(nil),                                 // 3: pb.ReplicationState
	(*ReplicationPeerDescription)(nil),                       // 4: pb.ReplicationPeerDescription
	(*ReplicationHLogPosition)(nil),                          // 5: pb.ReplicationHLogPosition
	(*AddReplicationPeerRequest)(nil),                        // 6: pb.AddReplicationPeerRequest
	(*AddReplicationPeerResponse)(nil),                       // 7: pb.AddReplicationPeerResponse
	(*RemoveReplicationPeerRequest)(nil),                     // 8: pb.RemoveReplicationPeerRequest
	(*RemoveReplicationPeerResponse)(nil),                    // 9: pb.RemoveReplicationPeerResponse
	(*EnableReplicationPeerRequest)(nil),                     // 10: pb.EnableReplicationPeerRequest
	(*EnableReplicationPeerResponse)(nil),                    // 11: pb.EnableReplicationPeerResponse
	(*DisableReplicationPeerRequest)(nil),                    // 12: pb.DisableReplicationPeerRequest
	(*DisableReplicationPeerResponse)(nil),                   // 13: pb.DisableReplicationPeerResponse
	(*GetReplicationPeerConfigRequest)(nil),                  // 14: pb.GetReplicationPeerConfigRequest
	(*GetReplicationPeerConfigResponse)(nil),                 // 15: pb.GetReplicationPeerConfigResponse
	(*UpdateReplicationPeerConfigRequest)(nil),               // 16: pb.UpdateReplicationPeerConfigRequest
	(*UpdateReplicationPeerConfigResponse)(nil),              // 17: pb.UpdateReplicationPeerConfigResponse
	(*ListReplicationPeersRequest)(nil),                      // 18: pb.ListReplicationPeersRequest
	(*ListReplicationPeersResponse)(nil),                     // 19: pb.ListReplicationPeersResponse
	(*GetReplicationPeerStateRequest)(nil),                   // 20: pb.GetReplicationPeerStateRequest
	(*GetReplicationPeerStateResponse)(nil),                  // 21: pb.GetReplicationPeerStateResponse
	(*ReplicationPeerModificationSwitchRequest)(nil),         // 22: pb.ReplicationPeerModificationSwitchRequest
	(*ReplicationPeerModificationSwitchResponse)(nil),        // 23: pb.ReplicationPeerModificationSwitchResponse
	(*ReplicationPeerModificationState)(nil),                 // 24: pb.ReplicationPeerModificationState
	(*GetReplicationPeerModificationProceduresRequest)(nil),  // 25: pb.GetReplicationPeerModificationProceduresRequest
	(*GetReplicationPeerModificationProceduresResponse)(nil), // 26: pb.GetReplicationPeerModificationProceduresResponse
	(*IsReplicationPeerModificationEnabledRequest)(nil),      // 27: pb.IsReplicationPeerModificationEnabledRequest
	(*IsReplicationPeerModificationEnabledResponse)(nil),     // 28: pb.IsReplicationPeerModificationEnabledResponse
	(*TableName)(nil),                                        // 29: pb.TableName
	(*BytesBytesPair)(nil),                                   // 30: pb.BytesBytesPair
	(*NameStringPair)(nil),                                   // 31: pb.NameStringPair
	(*Procedure)(nil),                                        // 32: pb.Procedure
}
var file_Replication_proto_depIdxs = []int32{
	29, // 0: pb.TableCF.table_name:type_name -> pb.TableName
	30, // 1: pb.ReplicationPeer.data:type_name -> pb.BytesBytesPair
	31, // 2: pb.ReplicationPeer.configuration:type_name -> pb.NameStringPair
	1,  // 3: pb.ReplicationPeer.table_cfs:type_name -> pb.TableCF
	1,  // 4: pb.ReplicationPeer.exclude_table_cfs:type_name -> pb.TableCF
	0,  // 5: pb.ReplicationState.state:type_name -> pb.ReplicationState.State
	3,  // 6: pb.ReplicationPeerDescription.state:type_name -> pb.ReplicationState
	2,  // 7: pb.ReplicationPeerDescription.config:type_name -> pb.ReplicationPeer
	2,  // 8: pb.AddReplicationPeerRequest.peer_config:type_name -> pb.ReplicationPeer
	3,  // 9: pb.AddReplicationPeerRequest.peer_state:type_name -> pb.ReplicationState
	2,  // 10: pb.GetReplicationPeerConfigResponse.peer_config:type_name -> pb.ReplicationPeer
	2,  // 11: pb.UpdateReplicationPeerConfigRequest.peer_config:type_name -> pb.ReplicationPeer
	4,  // 12: pb.ListReplicationPeersResponse.peer_desc:type_name -> pb.ReplicationPeerDescription
	32, // 13: pb.GetReplicationPeerModificationProceduresResponse.procedure:type_name -> pb.Procedure
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_Replication_proto_init() }
func file_Replication_proto_init() {
	if File_Replication_proto != nil {
		return
	}
	file_HBase_proto_init()
	file_Procedure_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Replication_proto_rawDesc), len(file_Replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Replication_proto_goTypes,
		DependencyIndexes: file_Replication_proto_depIdxs,
		EnumInfos:         file_Replication_proto_enumTypes,
		MessageInfos:      file_Replication_proto_msgTypes,
	}.Build()
	File_Replication_proto = out.File
	file_Replication_proto_goTypes = nil
	file_Replication_proto_depIdxs = nil
}
