// Code generated by protoc-gen-go.
// source: SecureBulkLoad.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SecureBulkLoadHFilesRequest struct {
	FamilyPath       []*BulkLoadHFileRequest_FamilyPath `protobuf:"bytes,1,rep,name=family_path,json=familyPath" json:"family_path,omitempty"`
	AssignSeqNum     *bool                              `protobuf:"varint,2,opt,name=assign_seq_num,json=assignSeqNum" json:"assign_seq_num,omitempty"`
	FsToken          *DelegationToken                   `protobuf:"bytes,3,req,name=fs_token,json=fsToken" json:"fs_token,omitempty"`
	BulkToken        *string                            `protobuf:"bytes,4,req,name=bulk_token,json=bulkToken" json:"bulk_token,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *SecureBulkLoadHFilesRequest) Reset()                    { *m = SecureBulkLoadHFilesRequest{} }
func (m *SecureBulkLoadHFilesRequest) String() string            { return proto.CompactTextString(m) }
func (*SecureBulkLoadHFilesRequest) ProtoMessage()               {}
func (*SecureBulkLoadHFilesRequest) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{0} }

func (m *SecureBulkLoadHFilesRequest) GetFamilyPath() []*BulkLoadHFileRequest_FamilyPath {
	if m != nil {
		return m.FamilyPath
	}
	return nil
}

func (m *SecureBulkLoadHFilesRequest) GetAssignSeqNum() bool {
	if m != nil && m.AssignSeqNum != nil {
		return *m.AssignSeqNum
	}
	return false
}

func (m *SecureBulkLoadHFilesRequest) GetFsToken() *DelegationToken {
	if m != nil {
		return m.FsToken
	}
	return nil
}

func (m *SecureBulkLoadHFilesRequest) GetBulkToken() string {
	if m != nil && m.BulkToken != nil {
		return *m.BulkToken
	}
	return ""
}

type SecureBulkLoadHFilesResponse struct {
	Loaded           *bool  `protobuf:"varint,1,req,name=loaded" json:"loaded,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SecureBulkLoadHFilesResponse) Reset()                    { *m = SecureBulkLoadHFilesResponse{} }
func (m *SecureBulkLoadHFilesResponse) String() string            { return proto.CompactTextString(m) }
func (*SecureBulkLoadHFilesResponse) ProtoMessage()               {}
func (*SecureBulkLoadHFilesResponse) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{1} }

func (m *SecureBulkLoadHFilesResponse) GetLoaded() bool {
	if m != nil && m.Loaded != nil {
		return *m.Loaded
	}
	return false
}

type DelegationToken struct {
	Identifier       []byte  `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Password         []byte  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Kind             *string `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Service          *string `protobuf:"bytes,4,opt,name=service" json:"service,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DelegationToken) Reset()                    { *m = DelegationToken{} }
func (m *DelegationToken) String() string            { return proto.CompactTextString(m) }
func (*DelegationToken) ProtoMessage()               {}
func (*DelegationToken) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{2} }

func (m *DelegationToken) GetIdentifier() []byte {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *DelegationToken) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *DelegationToken) GetKind() string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ""
}

func (m *DelegationToken) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

type PrepareBulkLoadRequest struct {
	TableName        *TableName `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PrepareBulkLoadRequest) Reset()                    { *m = PrepareBulkLoadRequest{} }
func (m *PrepareBulkLoadRequest) String() string            { return proto.CompactTextString(m) }
func (*PrepareBulkLoadRequest) ProtoMessage()               {}
func (*PrepareBulkLoadRequest) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{3} }

func (m *PrepareBulkLoadRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

type PrepareBulkLoadResponse struct {
	BulkToken        *string `protobuf:"bytes,1,req,name=bulk_token,json=bulkToken" json:"bulk_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrepareBulkLoadResponse) Reset()                    { *m = PrepareBulkLoadResponse{} }
func (m *PrepareBulkLoadResponse) String() string            { return proto.CompactTextString(m) }
func (*PrepareBulkLoadResponse) ProtoMessage()               {}
func (*PrepareBulkLoadResponse) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{4} }

func (m *PrepareBulkLoadResponse) GetBulkToken() string {
	if m != nil && m.BulkToken != nil {
		return *m.BulkToken
	}
	return ""
}

type CleanupBulkLoadRequest struct {
	BulkToken        *string `protobuf:"bytes,1,req,name=bulk_token,json=bulkToken" json:"bulk_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CleanupBulkLoadRequest) Reset()                    { *m = CleanupBulkLoadRequest{} }
func (m *CleanupBulkLoadRequest) String() string            { return proto.CompactTextString(m) }
func (*CleanupBulkLoadRequest) ProtoMessage()               {}
func (*CleanupBulkLoadRequest) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{5} }

func (m *CleanupBulkLoadRequest) GetBulkToken() string {
	if m != nil && m.BulkToken != nil {
		return *m.BulkToken
	}
	return ""
}

type CleanupBulkLoadResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CleanupBulkLoadResponse) Reset()                    { *m = CleanupBulkLoadResponse{} }
func (m *CleanupBulkLoadResponse) String() string            { return proto.CompactTextString(m) }
func (*CleanupBulkLoadResponse) ProtoMessage()               {}
func (*CleanupBulkLoadResponse) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{6} }

func init() {
	proto.RegisterType((*SecureBulkLoadHFilesRequest)(nil), "pb.SecureBulkLoadHFilesRequest")
	proto.RegisterType((*SecureBulkLoadHFilesResponse)(nil), "pb.SecureBulkLoadHFilesResponse")
	proto.RegisterType((*DelegationToken)(nil), "pb.DelegationToken")
	proto.RegisterType((*PrepareBulkLoadRequest)(nil), "pb.PrepareBulkLoadRequest")
	proto.RegisterType((*PrepareBulkLoadResponse)(nil), "pb.PrepareBulkLoadResponse")
	proto.RegisterType((*CleanupBulkLoadRequest)(nil), "pb.CleanupBulkLoadRequest")
	proto.RegisterType((*CleanupBulkLoadResponse)(nil), "pb.CleanupBulkLoadResponse")
}

var fileDescriptor26 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x95, 0xbb, 0x89, 0xb5, 0xb7, 0x85, 0x49, 0x06, 0xba, 0x92, 0xf1, 0x51, 0x05, 0x1e, 0x2a,
	0x84, 0xf2, 0xd0, 0x07, 0xe0, 0xb9, 0x9b, 0xaa, 0x6a, 0x42, 0x53, 0x95, 0xee, 0x85, 0xa7, 0xc8,
	0x69, 0x6e, 0x5a, 0xab, 0xa9, 0xed, 0xc6, 0x09, 0x08, 0xf1, 0x07, 0x10, 0xbf, 0x82, 0x9f, 0xc5,
	0xcf, 0xc1, 0x4e, 0xd2, 0x42, 0xb3, 0x8e, 0xbd, 0xdd, 0x7b, 0x7c, 0x6e, 0xee, 0x39, 0xc7, 0x31,
	0x3c, 0x99, 0xe1, 0x3c, 0x4f, 0x71, 0x94, 0x27, 0xab, 0x4f, 0x92, 0x45, 0x9e, 0x4a, 0x65, 0x26,
	0x69, 0x43, 0x85, 0x4e, 0x7b, 0x32, 0x62, 0x1a, 0x4b, 0xc0, 0xe9, 0x5c, 0x24, 0x1c, 0x45, 0x56,
	0x76, 0xee, 0x6f, 0x02, 0xe7, 0xfb, 0x73, 0x93, 0x31, 0x4f, 0x50, 0xfb, 0xb8, 0xc9, 0x51, 0x67,
	0xf4, 0x12, 0xda, 0x31, 0x5b, 0xf3, 0xe4, 0x5b, 0xa0, 0x58, 0xb6, 0xec, 0x91, 0xfe, 0xd1, 0xa0,
	0x3d, 0x7c, 0xed, 0xa9, 0xd0, 0xdb, 0xe3, 0x57, 0x74, 0x6f, 0x5c, 0x70, 0xa7, 0x86, 0xea, 0x43,
	0xbc, 0xab, 0xe9, 0x1b, 0x78, 0xc4, 0xb4, 0xe6, 0x0b, 0x11, 0x68, 0xdc, 0x04, 0x22, 0x5f, 0xf7,
	0x1a, 0x7d, 0x32, 0x68, 0xfa, 0x9d, 0x12, 0x9d, 0xe1, 0xe6, 0x3a, 0x5f, 0x53, 0x0f, 0x9a, 0xb1,
	0x0e, 0x32, 0xb9, 0x42, 0xd1, 0x3b, 0xea, 0x37, 0xcc, 0xa2, 0xc7, 0x76, 0xd1, 0x25, 0x26, 0xb8,
	0x60, 0x19, 0x97, 0xe2, 0xc6, 0x1e, 0xf9, 0x27, 0xb1, 0x2e, 0x0a, 0xfa, 0x02, 0x20, 0x34, 0x22,
	0xaa, 0x89, 0x63, 0x33, 0xd1, 0xf2, 0x5b, 0x16, 0x29, 0x8e, 0xdd, 0xf7, 0xf0, 0xfc, 0xb0, 0x33,
	0xad, 0xa4, 0xd0, 0x48, 0xbb, 0xf0, 0x20, 0x31, 0x28, 0x46, 0xc6, 0x55, 0xc3, 0x88, 0xa9, 0x3a,
	0xf7, 0x3b, 0x9c, 0xd6, 0x56, 0xd2, 0x97, 0x00, 0x3c, 0x32, 0xa1, 0xf1, 0x98, 0x63, 0x6a, 0xe8,
	0x64, 0xd0, 0xf1, 0xff, 0x41, 0xa8, 0x03, 0x4d, 0x65, 0xac, 0x7c, 0x95, 0x69, 0x54, 0x38, 0xeb,
	0xf8, 0xbb, 0x9e, 0x52, 0x38, 0x5e, 0x71, 0x11, 0x19, 0x47, 0xc4, 0xe8, 0x2b, 0x6a, 0xda, 0x83,
	0x13, 0x8d, 0xe9, 0x17, 0x3e, 0x47, 0x23, 0xdb, 0xc2, 0xdb, 0xd6, 0x1d, 0x43, 0x77, 0x9a, 0xa2,
	0x62, 0x7f, 0x55, 0x6f, 0x6f, 0xe2, 0x1d, 0x40, 0xc6, 0xc2, 0x04, 0x03, 0xc1, 0xd6, 0x58, 0x48,
	0x6e, 0x0f, 0x1f, 0xda, 0x7c, 0x6e, 0x2c, 0x7a, 0x6d, 0x40, 0xbf, 0x95, 0x6d, 0x4b, 0xf7, 0x23,
	0x9c, 0xdd, 0xfa, 0x4e, 0xe5, 0x7b, 0x3f, 0x36, 0x52, 0x8f, 0xed, 0x03, 0x74, 0x2f, 0x12, 0x64,
	0x22, 0x57, 0x75, 0x05, 0xf7, 0x0c, 0x3e, 0x83, 0xb3, 0x5b, 0x83, 0xe5, 0xca, 0xe1, 0xcf, 0x06,
	0x3c, 0xdd, 0xbf, 0x8b, 0x59, 0xe9, 0x97, 0x5e, 0xc1, 0x69, 0x4d, 0x27, 0x75, 0xac, 0xa9, 0xc3,
	0x21, 0x38, 0xe7, 0x07, 0xcf, 0x2a, 0x63, 0x9f, 0xeb, 0x4f, 0xa0, 0xbc, 0x70, 0xfa, 0xca, 0x0e,
	0xfd, 0xe7, 0x27, 0x77, 0xfa, 0x77, 0x13, 0xaa, 0x4f, 0x1b, 0x99, 0x35, 0x6f, 0xa5, 0xcc, 0xc3,
	0x49, 0x95, 0x32, 0xef, 0x08, 0x63, 0x74, 0x05, 0x6f, 0x65, 0xba, 0xf0, 0x98, 0x62, 0xf3, 0x25,
	0x7a, 0x4b, 0x16, 0x49, 0xa9, 0xbc, 0x65, 0xb8, 0x7b, 0xa1, 0x61, 0x1e, 0x7b, 0x0b, 0x14, 0x98,
	0xb2, 0x0c, 0xa3, 0x51, 0xcd, 0xd2, 0xd4, 0x32, 0xf4, 0x84, 0xfc, 0x20, 0xe4, 0x17, 0x21, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x1e, 0x4e, 0x78, 0xf4, 0x03, 0x00, 0x00,
}
